[package]
name = "chip-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "*"
piet-common = "0.5.0"
piet = "0.5.0"
minifb = "0.23.0"
